repos:
  - repo: https://github.com/psf/black
    rev: '24.1.0'
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.12.10'
    hooks:
      - id: ruff

  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
