name: Backend tests

on:
  push:
    paths:
      - 'backend/**'
      - 'geny/**'
      - 'geny_ai/**'
      - 'memory.py'
      - 'requirements.txt'
      - '.github/workflows/backend-tests.yml'
      - 'google/**'
      - 'scripts/**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
      - name: Run backend tests
        run: |
          python -m pytest backend/tests -q
