name: CI

on:
  push:
    branches: [main, feat/auto-fixes-clean, 'fix/**']
  pull_request:
    branches: [main, feat/auto-fixes-clean]

jobs:
  test:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        # Tests are mocked to avoid requiring live API keys. If you want to run
        # live integration tests, add GENAI_API_KEY to repository secrets and
        # create a separate workflow/job that injects it.
        run: |
          pytest -q
