name: Flutter Tests

on:
  push:
    paths:
      - 'android_app/**'
      - '.github/workflows/flutter_tests.yml'
  pull_request:
    paths:
      - 'android_app/**'

jobs:
  flutter-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: |
          cd android_app/app
          flutter pub get

      - name: Check formatting
        run: |
          cd android_app/app
          flutter format --set-exit-if-changed .

      - name: Analyze
        run: |
          cd android_app/app
          flutter analyze

      - name: Run tests
        run: |
          cd android_app/app
          flutter test --reporter=expanded
