name: Integration tests (Gemini)

on:
  workflow_dispatch:
  push:
    branches: [ feat/auto-fixes-clean ]

jobs:
  gemini_integration:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.12'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Gemini integration test
        env:
          GENAI_API_KEY: ${{ secrets.GENAI_API_KEY }}
        run: |
          pytest -q test_gemini_flash.py
