name: Post-deploy smoke tests (manual)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Base URL to test (e.g. https://geny-1.onrender.com)'
        required: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Health check
        run: |
          URL=${{ github.event.inputs.url }}
          echo "Checking $URL/healthz"
          curl -sSf "$URL/healthz" || (echo 'healthz failed' && exit 1)
          echo 'healthz OK'

      - name: Chat endpoint test
        run: |
          URL=${{ github.event.inputs.url }}
          echo "POST $URL/chat"
          http_code=$(curl -s -o /tmp/chat_resp -w "%{http_code}" -X POST -H "Content-Type: application/json" -d '{"message":"CI smoke"}' "$URL/chat" )
          if [ "$http_code" != "200" ]; then
            echo "CHAT-FAILED status=$http_code"
            cat /tmp/chat_resp || true
            exit 1
          fi
          echo "CHAT OK"
          cat /tmp/chat_resp || true
