name: Secret checker (manual)

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository secrets (REST API)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          API_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/secrets"
          echo "Querying $API_URL"
          resp=$(curl -sS -H "Authorization: Bearer $GITHUB_TOKEN" "$API_URL")
          if [ -z "$resp" ]; then
            echo "Could not list repository secrets via API"
            exit 1
          fi
          names=$(echo "$resp" | jq -r '.secrets[].name' || true)
          needed=("GENAI_API_KEY" "RENDER_SERVICE_ID" "RENDER_API_TOKEN" "ANDROID_KEYSTORE_BASE64")
          missing=()
          for s in "${needed[@]}"; do
            if ! echo "$names" | grep -q "^$s$"; then
              missing+=("$s")
            fi
          done
          if [ ${#missing[@]} -eq 0 ]; then
            echo "All required secrets present (checked via REST API)."
          else
            echo "Missing secrets: ${missing[*]}"
            exit 1
          fi
