name: Secret checker (manual)

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository secrets
        run: |
          needed=("GENAI_API_KEY" "RENDER_SERVICE_ID" "RENDER_API_TOKEN" "ANDROID_KEYSTORE_BASE64")
          missing=()
          for s in "${needed[@]}"; do
            if ! gh secret list --repo $GITHUB_REPOSITORY | grep -q "^$s\b" 2>/dev/null; then
              missing+=("$s")
            fi
          done
          if [ ${#missing[@]} -eq 0 ]; then
            echo "All required secrets appear present (note: this checks GH secrets list, not content)."
          else
            echo "Missing secrets: ${missing[*]}"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
